### ISSUE TITLE
[Question]: VS Code debugger

### ISSUE THREAD

**Issue by matthewfala** [moosecasa/vscode-acutest-test-adapter#2]
### Your suggestion

Hi James,
Thank you for your work on the acutest-test-adapter.
Is there any way you know of to run acutests with VSCode debugging? I'm new to acutest and a project I am working on uses it. I would love to be able to set break points when I run my test code.

Thanks!
Matt

**Comment by james2432** [comment]
I think you'd have to compile the tests in debug mode and launch them with a launch argument such as:

https://github.com/mity/acutest#running-unit-tests

This is executing the tests automatically and I don't see a way to easily tie in to the debugger as this is an extension of an extension

**Comment by matthewfala** [comment]
Thank you for the suggestion. Okay, now
I'm running the tests now using a launch.json file
```
{
    
    "configurations": [
        {
        
            "cwd": "${workspaceFolder}/build",
            "program": "${workspaceFolder}/build/bin/flb-it-aws_util",
            "name": "flb-it-aws_util",
            "type": "cppdbg",
            "request": "launch",
            "MIMode": "lldb",
        }
    ]
}
```

If I add a break point in acutest.h, VSCode can pause there.
![Screen Shot 2021-08-27 at 6 58 20 PM](https://user-images.githubusercontent.com/34408404/131202689-16dd9283-02e2-416a-92fe-bce37e95730e.png)

But unfortunately, it will not detect the VSCode breakpoints inside my test.
![Screen Shot 2021-08-27 at 6 58 46 PM](https://user-images.githubusercontent.com/34408404/131202694-2a1930c2-403c-4ac9-b9c8-b6912c5dc314.png)

Any idea how I could get the code to trigger the break point inside my test?
I've been trying to get debugging set up most of the day, and any pointers you could give me would be appreciated! 😁

**Comment by matthewfala** [comment]
Got it. The issue is that Acutest forks the process when running a test. The child process is not followed by the debugger. I modified the Acutest.h script to conditionally change the test from running on the child to parent for the test I want to debug. Thanks for your help.

**Comment by james2432** [comment]
Might want to suggest that or your changes in https://github.com/mity/acutest/issues

To be easier to debug tests


Could be gdb needs to be configured to follow child processes too:

https://stackoverflow.com/questions/46627758/visual-studio-code-debugging-child-process-not-working

**Comment by matthewfala** [comment]
The problem with following the child process is that the fork to the first test is taken. When that test ends and the child terminates, so will gdb. My solution is to run the test on parent and switch the runner to child only when my specific test is reached. It's not extremely elegant, and I don't think that it will be an accepted change to acutest.
